{{- if .Values.Lavalink.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lavalink-music.serviceAccountName" . }}
  labels:
    {{- include "lavalink-music.labels" . | nindent 4 }}
  {{- with .Values.Lavalink.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
