# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["./values.yaml"]'
        env:
          TOKEN: '${{ secrets.DISCORD_TOKEN }}'
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
        
      - name: Deploy via Helm
        run: |
          cd ./lavaLink
          if helm status lavaLink -n lavalink; then
            helm upgrade lavaLink  -n lavalink . 
          else 
            helm install lavaLink -n lavalink  .
          fi
      - name: Deploy via Helm
        run: |
          cd ./LavaMusic
          if helm status LavaMusic -n lavalink; then
            helm upgrade LavaMusic  -n lavalink . 
          else 
            helm install LavaMusic -n lavalink  .
          fi
      
      
          

     
