# This is a basic workflow to help you get started with Actions

name: LavalinkHelm

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  workflow_run:
    workflows: [build_and_push_lavamusic]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["./LavaMusic/values.yaml"]'
        env:
          TOKEN: '${{ secrets.DISCORD_TOKEN }}'
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: '{"clientId":"${{secrets.CLIENT_ID}}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
        
      - name: Deploy via Helm
        run: |
          cd ./lavaLink
          if helm status lavalink -n lavalink; then
            helm upgrade lavalink  -n lavalink . 
          else 
            helm install lavalink -n lavalink  .
          fi
      - name: Deploy via Helm
        run: |
          cd ./LavaMusic
          if helm status lavamusic -n lavalink; then
            helm upgrade lavamusic  -n lavalink . 
          else 
            helm install lavamusic -n lavalink  .
          fi
      
      
          

     
